### PR TITLE
Add preauthorizations and refunds

### PR DESCRIPTION
**Pull request by acwebionate**
Added classes to be able to request preauthorizations and refunds

### CODE REVIEW

**Comment by flippingbits** [comment]
Thank you for your work. Can you add a test for `Refund`?

**Comment by acwebionate** [comment]
I've added a few basic tests. If you'd like to have some more please be patient, since I'll be working on another project the upcoming days ;)

**Comment by flippingbits** [comment]
Have you received my email containing questions regarding this PR?

**Comment by mkilling** [comment]
What's the status of this?

**Comment by flippingbits** [comment]
I'm waiting for acwebionate to answer some questions regarding this PR.

**Comment by acwebionate** [comment]
Sorry, was (a little) off the grid for a few days. I've just send you an answer (via email) to your question @flippingbits.

**Pull request merged**
