### PR TITLE
Add missing webhook attributes

### PR DESCRIPTION
**Pull request by thmsobrmlr**
I found that webhook attributes `active` and `app_id` were missing. This pull request adds them. I also had to lock the version of rspec at 2.13.0 as the project still uses the old syntax.

https://www.paymill.com/de-de/dokumentation/referenz/api-referenz/#list-webhooks

### CODE REVIEW

**Comment by thmsobrmlr** [comment]
@flippingbits Any comments on this?

**Comment by flippingbits** [comment]
Looks good!
We might update to the latest RSpec version soon.

**Comment by zamith** [comment]
The update to RSpec 3 has been done in #48.

**Comment by thmsobrmlr** [comment]
Updated spec here accordingly. Anything missing?

**Comment by flippingbits** [comment]
Looks good to me. Thank you!

**Pull request merged**
