### PR TITLE
Normalizes post params, fixes #32

### LINKED ISSUE #32: Ignoring event_types array when creating a Webhook
Theres a bug when creating a url webhook, it ignores the event_types array, taking just the first element of it.

### PR DESCRIPTION
**Pull request by zamith**

### CODE REVIEW

**Comment by flippingbits** [comment]
You broke the build :)

**Comment by zamith** [comment]
@flippingbits I need to ignore caps... :S

**Comment by flippingbits** [comment]
I just had a closer look at your code and I don't like the idea of extending the Hash class.
Do you see any other way?

**Comment by zamith** [comment]
@flippingbits Yes, me neither. I'll rewrite it, as a private method.

**Comment by zamith** [comment]
@flippingbits What do you think?

**Comment by flippingbits** [comment]
You should put `flatten_hash_keys` and `normalize_params` into a module or class (e.g. `Paymill::Request::Connection`).

**Comment by zamith** [comment]
@flippingbits I don't like that to much because it feels odd that the connection should know about flattening hashes (maybe `normalize_params` could go into it). I created a `Helpers` class for the `Request` and put it there.

What do you think?

**Comment by flippingbits** [comment]
you only need them in Connection, don't you? Then, why don't you place the methods there?

**Comment by zamith** [comment]
@flippingbits Just to keep the responsibilities decoupled.

**Comment by flippingbits** [comment]
Wow, this was a long road. Thank you for your patience :)

**Comment by zamith** [comment]
@flippingbits It's fun. :)

**Pull request merged**
