### PR TITLE
Adds logging to paymill

### PR DESCRIPTION
**Pull request by zamith**
I also added some tests for the configurations, just in case.

### CODE REVIEW

**Comment by flippingbits** [comment]
Looks good to me. :+1:  What about a development section in the readme that explains how to use the logging?

**Comment by zamith** [comment]
Sure. Forgot about that, I'll add ASAP.

**Comment by flippingbits** [comment]
Thanks a lot :)

**Comment by zamith** [comment]
@flippingbits What do you think?

**Comment by flippingbits** [comment]
Thanks a lot :+1:

**Pull request merged**
