### PR TITLE
Better configuration for Paymill gem

### PR DESCRIPTION
**Pull request by zamith**
- Allows configuration of base endpoint, port, version and adds a
  development mode
- Creates a Paymill::Configuration class for all configs
- Deprecates Paymill.api_key and Paymill.api_key=
- Updates README

### CODE REVIEW

**Comment by flippingbits** [comment]
I don't like the approach of having a Configuration class for just four config options.
I prefer moving these options into the Paymill namespace again, e.g.:

```
Paymill.api_key
Paymill.api_base
```

and so on ;)

A configuration class might be useful if we add a custom configuration DSL for the paymill gem. But I don't think that we need one.

What do you think about moving these config methods back to `Paymill`?

**Comment by zamith** [comment]
I had them there originally, but it felt there was too much "noise" in that class, so I decided to extract a new class, following braintree's ruby gem approach.

I'm not creating a `configure` method or anything, it's the exact same approach, with the class methods and variables, but with a different namespace, to remove some of the clutter.

**Comment by flippingbits** [comment]
Nonetheless it's a breaking change. It will break all configurations.

I don't see the need for it. ;)

**Comment by zamith** [comment]
I left the `api_key` method on the `Paymill` module, I just deprecated it. 

I need these configs for fake_paymill, if you're not confortable with adding a new class I can move them to `Paymill`. You are not opposed to having the configs, right?

**Comment by flippingbits** [comment]
Nope, I'm fine with the new configs. Just move them to `Paymill`.

Thanks! :)

**Comment by zamith** [comment]
@flippingbits Is this it?

**Comment by flippingbits** [comment]
Yes, thank you! :)

**Pull request merged**
