### PR TITLE
Support v2.1 of PAYMILL API

### PR DESCRIPTION
**Pull request by nikoloff**
- No changes in interface of create, all, find actions (class methods).
- Delete action is now an instance method (e.g. client.delete)
- Update is done via setters on the instance and calling e.g. client.update will go to PAYMILL endpoint

### CODE REVIEW

**Comment by zamith** [comment]
Why would you want to change the gem name, change the rubies that are tested, remove some development gems, remove @flippingbits credit and more, just to adds 2.1 support?

Was this supposed to be your own repo?

**Comment by flippingbits** [comment]
Sorry, but I can't merge this PR.

**Comment by nikoloff** [comment]
Hi @zamith and @flippingbits,
Sorry about the update in credits, I did not check that before creating this PR.
If I update/restore paymill.gemspec, LICENSE and README, will there be a chance this PR to be merged, or the diff is just too big?

**Comment by zamith** [comment]
It is ultimately up to Stefan, but in my opinion there are too many changes unrelated to the issue. Please change nothing but what is needed to get 2.1 support, as well as accompanying tests, and open a new pr. 

That will give us a better baseline to start a discussion.

Thanks for the effort, anyway.

**Comment by flippingbits** [comment]
@nikoloff Sure, I'd love to have 2.1 support in this gem.
Maybe you should create another minimalistic pull request that is changing only as much as needed for upgrading to version 2.1 of the Paymill API.

**Comment by l0ck3** [comment]
I would agree with that. 
Thanks anyway. Your contribution is appreciated.

**Pull request closed without merging**
