### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by max-power**

### CODE REVIEW

**Comment by flippingbits** [comment]
Paymill will introduce a new version of its API pretty soon.
That said I don't want to merge Paymill:Naming since the names of the API endpoints will change.
Can you remove commits relating to this?

**Comment by max-power** [comment]
yeah, don't pull. maybe it is better to wait for the new api.

Am 29.10.2012 um 14:52 schrieb Stefan notifications@github.com:

**Comment by LosVogas** [comment]
V2 is already online. isn't it?

**Comment by flippingbits** [comment]
Yes, I'll update the gem ASAP. Contributions are welcome! :)

**Comment by Traxmaxx** [comment]
Do they have a comparison somewhere about the changes?

**Comment by max-power** [comment]
nothing much changed.
- there is /v2/ now in the url.
- a lot more resources.

i have a new experimental branch. will put it up within the next hour.

Am 12.11.2012 um 11:31 schrieb Alexander Rösel notifications@github.com:

**Comment by max-power** [comment]
https://github.com/max-power/paymill-ruby/tree/rewrite

**Comment by Traxmaxx** [comment]
Perfect, I'll take a look on it later : )

**Comment by flippingbits** [comment]
The changes are actually:
- the URL is now https://api.paymill.de/v2/ instead of https://api.paymill.de/v1/
- they renamed creditcards to payments

I'll ping the paymill guys and ask if there's anything else we should take care of.

**Comment by flippingbits** [comment]
FYI: I've started working on the update: f6168582 and 4a8cb7d5.

**Comment by LosVogas** [comment]
Since the Update. I cannot create new Payments (CreditCards) while inserting a created token.

**Comment by flippingbits** [comment]
Can you provide a code example to show us what you're doing?

**Comment by LosVogas** [comment]
OK I am logged in. 

token = "tok_7eb9bb95bfb229f2d8b1"
Paymill::Payment.create(token)
or
Paymill::Payment.create(token, client.id)

both don't work.

**Comment by flippingbits** [comment]
Hm, seems that we've problems loading `paymill/payment`. I'll dive into it.

**Comment by LosVogas** [comment]
Naa, forget it.  I am an idiot. 
Paymill::Payment.create(token: token)

works fine...sorry

**Comment by flippingbits** [comment]
:)

**Comment by flippingbits** [comment]
@max-power, do you want to update your pull request?

**Comment by max-power** [comment]
i don't know if you want to pull this, because there are a lot of changes and not much tests.
also i'd like to typecast the results form pay mill, because the results are quite inconsistent. the "amount" field in Paymill::Transaction is a String, while the origin_amount come as Integer. 
furthermore the unix-timestamps could be converter to proper time instances. same for money.
but i'm struggling a bit of implementing it.

**Comment by d0mme-zz** [comment]
Do you face any more issues on our API? Otherwise I'd talk to some of our dev members to solve your problems. :) 

Kind regards, 
Dominic

**Comment by flippingbits** [comment]
This pull request is too big. If you want your commits merged please break them down in multiple smaller pull requests.

**Pull request closed without merging**
