### PR TITLE
added response_code to preauthorization

### PR DESCRIPTION
**Pull request by acarpe**

### CODE REVIEW

**Comment by mpapis** [comment]
hmm, I do not see `response_code` in https://www.paymill.com/en-gb/documentation-3/reference/api-reference/#preauthorization-object - there is `response_code` in the response to creating a preauthorization, but the response is a transaction object https://www.paymill.com/en-gb/documentation-3/reference/api-reference/#create-new-preauthorization-with

**Comment by acarpe** [comment]
I see what you mean, the response_code is not part of preauthorization object.
Probably the misunderstanding is caused by the fact that when you try to create, for example, a preauthorization with 

``` ruby
Paymill::Preauthorization.create
```

it sticks to the following code

``` ruby
def create(attributes)
    response = Paymill.request(:post, "#{self.name.split("::").last.downcase}s", attributes)
    self.new(response["data"])
end
```

that is not returning a "Response" object but it returns the original object, the Preautorization in this case, in which we cannot access to the response attributes.
With this new understanding my pull request is obviously a workaround, I'll try to find the time to propose a different design.

WDYT?

**Comment by mpapis** [comment]
I will be working on it/similar problems in next 2 weeks, in this case I was thinking about adding dsl like `creates ...`, but there are other places that have lists or sub objects and I was thinking on adding dsl for them as well, maybe `has_one ...` and `has_many ...` ;)

**Comment by flippingbits** [comment]
I think I can close this PR.

**Pull request closed without merging**
